@HashProcessor.Api_HostAddress = https://localhost:7178

POST {{HashProcessor.Api_HostAddress}}/hashes
Accept: application/json

###

GET {{HashProcessor.Api_HostAddress}}/hashes
Accept: application/json

###